# Generated by Django 5.0.3 on 2024-05-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='gender',
            new_name='genre',
        ),
    ]
