# Generated by Django 5.0.3 on 2024-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_delete_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.CharField(max_length=15),
        ),
    ]
